### ISSUE TITLE
`global_tolerations` is ignored

### ISSUE THREAD

**Issue by 0x416e746f6e** [ethpandaops/optimism-package#118]
Using the following parameters:

```yaml
optimism_package:
  global_tolerations:
    - key: flashbots.net/kurtosis
      operator: Equal
      value: "false"
      effect: NoSchedule

  chains:
    - participants:
        - el_type: op-reth
          cl_type: op-node


      mev_params:
        builder_host: localhost
        builder_port: 8545

ethereum_package:
  global_tolerations:
    - key: flashbots.net/kurtosis
      operator: Equal
      value: "false"
      effect: NoSchedule

  participants:
    - el_type: reth
      cl_type: lighthouse

  network_params:
    preset: minimal
    genesis_delay: 5
    additional_preloaded_contracts: |-
      {
        "0x4e59b44847b379578588920cA78FbF26c0B4956C": {
          "balance": "0ETH",
          "code": "0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf3",
          "storage": {},
          "nonce": "1"
        }
      }

```

Deploys pods into k8s only with the following tolerations:

```yaml
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
```
