### ISSUE TITLE
Can't fire up Rollup-Boost with other builder

### ISSUE THREAD

**Issue by con5cience** [ethpandaops/optimism-package#162]
Hi there.

Getting this error when trying to stand up `rollup-boost`:
```
kurtosis run --enclave builder-devnet github.com/ethpandaops/optimism-package --args-file params.yaml

There was an error interpreting Starlark code 
Evaluation error: function launch accepts 11 positional arguments (13 given)
        at [github.com/ethpandaops/optimism-package/main.star:112:34]: run
        at [github.com/ethpandaops/optimism-package/src/l2.star:48:56]: launch_l2
        at [github.com/ethpandaops/optimism-package/src/participant_network.star:36:68]: launch_participant_network
        at [github.com/ethpandaops/optimism-package/src/el_cl_launcher.star:277:62]: launch
        at [github.com/ethpandaops/optimism-package/src/el/op-reth/op_reth_builder_launcher.star:98:17]: launch

Error encountered running Starlark code.
```

Here's my `params.yaml`:
```
optimism_package:
  observability:
    enabled: false
  chains:
    - participants:
        - el_type: op-geth
          el_log_level: ""
          el_extra_env_vars: {}
          el_extra_labels: {}
          el_extra_params: []
          el_tolerations: []
          el_volume_size: 0
          el_min_cpu: 0
          el_max_cpu: 0
          el_min_mem: 0
          el_max_mem: 0
          cl_type: op-node
          cl_log_level: ""
          cl_extra_env_vars: {}
          cl_extra_labels: {}
          cl_extra_params: []
          cl_tolerations: []
          cl_volume_size: 0
          cl_min_cpu: 0
          cl_max_cpu: 0
          cl_min_mem: 0
          cl_max_mem: 0
          el_builder_type: op-reth
          el_builder_image: ghcr.io/some/image:latest
          cl_builder_type: op-node
      network_params:
        network: "kurtosis"
        network_id: "2151908"
        seconds_per_slot: 2
        name: "op-kurtosis"
        fjord_time_offset: 0
        granite_time_offset: 0
        fund_dev_accounts: true
      batcher_params:
        extra_params: []
      mev_params:
        rollup_boost_image: "flashbots/rollup-boost:latest"
      additional_services:
        - rollup-boost
  op_contract_deployer_params:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-deployer:v0.0.11
    l1_artifacts_locator: https://storage.googleapis.com/oplabs-contract-artifacts/artifacts-v1-c193a1863182092bc6cb723e523e8313a0f4b6e9c9636513927f1db74c047c15.tar.gz
    l2_artifacts_locator: https://storage.googleapis.com/oplabs-contract-artifacts/artifacts-v1-c193a1863182092bc6cb723e523e8313a0f4b6e9c9636513927f1db74c047c15.tar.gz
  global_log_level: "info"
  global_node_selectors: {}
  global_tolerations: []
  persistent: false

ethereum_package:
  network_params:
    preset: minimal
    genesis_delay: 5
    additional_preloaded_contracts: '
      {
        "0x4e59b44847b379578588920cA78FbF26c0B4956C": {
          "balance": "0ETH",
          "code": "0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf3",
          "storage": {},
          "nonce": "1"
        }
      }
    '
```

I've lifted this mostly from defaults in the repo, so I'm not sure what the deal is. Please let it be something trivial. :)

**Comment by SozinM** [comment]
+1 to the issue

**Comment by con5cience** [comment]
> Hi! You may try again from the main branch (or [this](https://github.com/ethpandaops/optimism-package/pull/163) ) Also here's example config to try:
> 
> ```
> <snip>
> ```
> 
> Note that you should use teku CL, as lighthouse doesn't work for now

Thanks for the suggestion -- While this does seem to stand up the enclave, it omits the `el_builder_type`, `el_builder_image`, and `cl_builder_type` parameters. Part of the requirement set I'm trying to satisfy involves implementing an external block builder behind Rollup-Boost as part of the configuration.

Is the implication that I should run the external builder in a separate workflow and use `mev_params` to point at it?

**Comment by SozinM** [comment]
Ah, yes, the main point of my snippet is 
```
ethereum_package:
  participants:
  - el_type: geth
    cl_type: teku
```
So you could add this to your snippet and put correct 
`el_builder_image`
