### ISSUE TITLE
No handle `log_level` in network params in `op-reth`

### ISSUE THREAD

**Issue by mateusfigmelo** [ethpandaops/optimism-package#179]
`el_log_level` in network params is now ignored.

```YAML
- participants:
      - el_type: op-reth
        el_log_level: "trace"
```
