### ISSUE TITLE
Inconsistent ID format in README example vs code validation

### ISSUE THREAD

**Issue by dhyaniarun1993** [ethpandaops/optimism-package#293]
# Description

The README example under Superchain configuration shows a superchain named with a dash:

```
superchains:
  superchain-a:
    enabled: true
    participants: ["2151908"]
```

However, using superchain-a as an ID results in the following error:
```
Evaluation error: fail: ID cannot contain '-': superchain-a
    at [src/util/id.star:4:13]: assert_id
```

The code explicitly rejects - in IDs via assert_id.
