### ISSUE TITLE
bug: additional_services can't be empty for ethereum_package

### ISSUE THREAD

**Issue by barnabasbusa** [ethpandaops/optimism-package#39]
```yaml
optimism_package:
  participants:
    - el_type: op-erigon
      cl_type: op-node
ethereum_package:
  participants:
    - el_type: geth
    - el_type: reth
  additional_services: []
```

error: 
```
Evaluation error: struct has no .network_params attribute
        at [github.com/ethpandaops/optimism-package/main.star:26:27]: run
```

if any service is launched, the error goes away. e.g:

```yaml
optimism_package:
  participants:
    - el_type: op-erigon
      cl_type: op-node
ethereum_package:
  participants:
    - el_type: geth
    - el_type: reth
  additional_services:
    - dora
```
