### ISSUE TITLE
Application failed: error in pipeline stage apply: error deploying OP chain

### ISSUE THREAD

**Issue by zhouop0** [ethpandaops/optimism-package#80]
```
optimism_package:
  chains:
    - participants:
        - el_type: op-geth
          cl_type: op-node
      additional_services:
        - blockscout
ethereum_package:
  participants:
    - el_type: geth
    - el_type: reth
  network_params:
    preset: minimal
  additional_services:
    - dora
    - blockscout
```
I run it on macOs Sonoma version 14.6.1. There are always some errors.  dora can not be started.

<img width="1500" alt="image" src="https://github.com/user-attachments/assets/0d801947-2229-4175-aa34-bd991d758f96">

 If I delete dora config.  It is error too.  like that:

```
optimism_package:
  chains:
    - participants:
        - el_type: op-geth
          cl_type: op-node
      additional_services:
        - blockscout
ethereum_package:
  participants:
    - el_type: geth
    - el_type: reth
  network_params:
    preset: minimal
  additional_services:
    - blockscout
```

t=2024-10-03T07:32:28+0000 lvl=info msg="deploying OP chain" stage=deploy-opchain id=0x000000000000000000000000000000000000000000000000000000000020d5e4
t=2024-10-03T07:32:28+0000 lvl=info msg="transaction broadcasted" stage=deploy-opchain id=0x4c8198805a3c5796489400680cc697d914a811df049a4255fdb65026eedd952c nonce=28
t=2024-10-03T07:32:33+0000 lvl=error msg="transaction failed on chain" stage=deploy-opchain id=0x4c8198805a3c5796489400680cc697d914a811df049a4255fdb65026eedd952c completed=1 total=1 hash=0x7d3b746f2264e524a11a62ec5dbc42d4d58c11a4e8ceab21e625da0227027ca5 nonce=28
Application failed: error in pipeline stage apply: error deploying OP chain: failed to broadcast: 1 error occurred:
	* transaction failed: 0x7d3b746f2264e524a11a62ec5dbc42d4d58c11a4e8ceab21e625da0227027ca5

<img width="1472" alt="image" src="https://github.com/user-attachments/assets/c312e9ba-57b0-479f-b1d2-2ea210168758">

I want to launch an L1 Ethereum node to interact with the L2 network. How can I do it ?

**Comment by barnabasbusa** [comment]
Your first issue is due to the fact that you are running an older dora image.
Try to run your scripts with `--image-download always` 

The second issue is taht you are redefining the ethereum_package's network_params but not including a necessary contract:
https://github.com/ethpandaops/optimism-package/blob/main/src/package_io/input_parser.star#L191

We by default use minimal preset, so you shouldn't need to redefine it.

You should be able to run 
```
optimism_package:
  chains:
    - participants:
        - el_type: op-geth
          cl_type: op-node
      additional_services:
        - blockscout
ethereum_package:
  participants:
    - el_type: geth
    - el_type: reth
  additional_services:
    - dora
    - blockscout
 ```
