### ISSUE TITLE
Request the example for deploying OP rollup to public testnet

### ISSUE THREAD

**Issue by lesterli** [ethpandaops/optimism-package#83]
Hello, we’re working on deploying an OP rollup on both a local L1 and Sepolia. The Kurtosis package is quite easy to use, and one command sets everything up. However, I haven’t found an example for deploying an OP rollup on a public testnet, like Sepolia. 
Could you confirm if the following configuration is suitable for spinning up an OP L2 chain on Sepolia?

```
optimism_package:
  chains:
    - participants:
        - el_type: op-geth
          cl_type: op-node
ethereum_package:
  network_params:
    network: sepolia
```

Additionally, our team is a start-up, we’ve made minimal modifications to the OP node codebase, would it be possible to modify the Kurtosis package to support spinning up a customized op-node?
